<?php

$_COS_LANG_MODULE['Delete'] = 'Slet';
$_COS_LANG_MODULE['Checkout'] = 'Checkout';
$_COS_LANG_MODULE['Repo has been deleted'] = 'Repo er blevet slettet';
$_COS_LANG_MODULE['Confirm removal of repo'] = 'Bekræft fjernelse af repo';
$_COS_LANG_MODULE['Enter repo URL (http|https)'] = 'Indtast repo URL (http | https)';
$_COS_LANG_MODULE['Add'] = 'Tilføje';
$_COS_LANG_MODULE['Not a correct repo URL'] = 'Ikke en korrekt repo URL';
$_COS_LANG_MODULE['Repo already exists'] = 'Repo findes allerede';
$_COS_LANG_MODULE['URL does not seem to be a git repo. If you know this is a git repo, please try again.'] = 'URL synes ikke at være en git repo. Hvis du ved, det er en git repo, prøv igen.';
$_COS_LANG_MODULE['Will now checkout repo'] = 'Vil nu kassen repo';
$_COS_LANG_MODULE['Exports: '] = 'Eksport:';
$_COS_LANG_MODULE['Fetching repo '] = 'Henter repo';
$_COS_LANG_MODULE['Could not checkout repo. Somethings went wrong. Try again later'] = 'Kunne ikke kassen repo. Somethings gik galt. Prøv igen senere';
$_COS_LANG_MODULE['Could not write to file system '] = 'Kunne ikke skrive til filen systemet';
$_COS_LANG_MODULE['Could not move all HTML assets'] = 'Kunne ikke flytte alle HTML aktiver';
$_COS_LANG_MODULE['You have a file in your css path which is not allowed. Found file: '] = 'Du har en fil i din css vej, som ikke er tilladt. Fundet fil:';
$_COS_LANG_MODULE['Found illigal options in <span class="notranslate"><b>format-arguments</b></span>: '] = 'Fundet illigal muligheder i <b><span class="notranslate">format-arguments</span></b> :';
$_COS_LANG_MODULE['Remove it from <b>meta.yaml</b>'] = 'Fjern den fra <b>meta.yaml</b>';
$_COS_LANG_MODULE['Epub fails! Mobi has no cover image. Specify this in a meta.yaml file'] = 'Epub mislykkes! Mobi har ingen dækning image. Angiv dette i en meta.yaml fil';
$_COS_LANG_MODULE['Done '] = 'Færdig';
$_COS_LANG_MODULE['Add a git repo'] = 'Tilføj en git repo';
$_COS_LANG_MODULE['Wait while generating site. This may take a minute or two'] = 'Vent mens generere site. Dette kan tage et minut eller to';
$_COS_LANG_MODULE['If no error were reported, you exports has been generated. '] = 'Hvis der blev rapporteret nogen fejl, er du eksporten blevet genereret.';
$_COS_LANG_MODULE['Remove it from your repo with: git rm -f '] = 'Tag det fra din repo med: git rm -f';
$_COS_LANG_MODULE['in type '] = 'type';
$_COS_LANG_MODULE['Error. You will need to have .md files written in markdown in your repo. No such files found!'] = 'Fejl. Du skal have .md filer skrevet i værdien i din repo. Ingen sådanne filer fundet!';
$_COS_LANG_MODULE['Failed to create export of type: '] = 'Kunne ikke oprette eksport af typen:';
