<?php

$_COS_LANG_MODULE['Delete'] = '删除';
$_COS_LANG_MODULE['Checkout'] = '结帐';
$_COS_LANG_MODULE['Repo has been deleted'] = '回购已被删除';
$_COS_LANG_MODULE['Confirm removal of repo'] = '确认删除回购';
$_COS_LANG_MODULE['Enter repo URL (http|https)'] = '进入回购网址（HTTP | HTTPS）';
$_COS_LANG_MODULE['Add'] = '添加';
$_COS_LANG_MODULE['Not a correct repo URL'] = '不正确的URL回购';
$_COS_LANG_MODULE['Repo already exists'] = '回购已存在';
$_COS_LANG_MODULE['URL does not seem to be a git repo. If you know this is a git repo, please try again.'] = 'URL似乎并没有成为一个git的回购。如果你知道这是一个git的回购，请重试。';
$_COS_LANG_MODULE['Will now checkout repo'] = '现在将签回购';
$_COS_LANG_MODULE['Exports: '] = '出口：';
$_COS_LANG_MODULE['Fetching repo '] = '取回购';
$_COS_LANG_MODULE['Could not checkout repo. Somethings went wrong. Try again later'] = '无法结帐回购。有些事情出了问题。请稍后再试';
$_COS_LANG_MODULE['Could not write to file system '] = '无法写入文件系统';
$_COS_LANG_MODULE['Could not move all HTML assets'] = '动弹不得全部HTML资产';
$_COS_LANG_MODULE['You have a file in your css path which is not allowed. Found file: '] = '你有你的CSS路径的文件，这是不允许的。找到的文件：';
$_COS_LANG_MODULE['Epub fails! Mobi has no cover image. Specify this in a meta.yaml file'] = 'EPUB失败！摩比没有封面图片。在meta.yaml文件中指定该';
$_COS_LANG_MODULE['Done '] = 'DONE';
$_COS_LANG_MODULE['Add a git repo'] = '添加一个git仓库';
$_COS_LANG_MODULE['Wait while generating site. This may take a minute or two'] = '稍候，生成网站。这可能需要一两分钟';
$_COS_LANG_MODULE['If no error were reported, you exports has been generated. '] = '如果没有错误的报道，你的出口已经产生。';
$_COS_LANG_MODULE['Remove it from your repo with: git rm -f '] = '混帐RM -f：从你的回购与中删除';
$_COS_LANG_MODULE['Error. You will need to have .md files written in markdown in your repo. No such files found!'] = '错误。你将需要有写在降价在回购.md文件。没有这样的文件，找到了！';
$_COS_LANG_MODULE['Failed to create export of type: '] = '无法创建类型的出口：';
