<?php


// Translation of file /modules/gitbook/module.php

$_COS_LANG_MODULE['Delete'] = 'Delete';
$_COS_LANG_MODULE['Checkout'] = 'Checkout';
$_COS_LANG_MODULE['Repo has been deleted'] = 'Repo has been deleted';
$_COS_LANG_MODULE['Confirm removal of repo'] = 'Confirm removal of repo';
$_COS_LANG_MODULE['Enter repo URL (http|https)'] = 'Enter repo URL (http|https)';
$_COS_LANG_MODULE['Add'] = 'Add';
$_COS_LANG_MODULE['Not a correct repo URL'] = 'Not a correct repo URL';
$_COS_LANG_MODULE['Repo already exists'] = 'Repo already exists';
$_COS_LANG_MODULE['URL does not seem to be a git repo. If you know this is a git repo, please try again.'] = 'URL does not seem to be a git repo. If you know this is a git repo, please try again.';
$_COS_LANG_MODULE['Will now checkout repo'] = 'Will now checkout repo';
$_COS_LANG_MODULE['Exports: '] = 'Exports: ';
$_COS_LANG_MODULE['Fetching repo '] = 'Fetching repo ';
$_COS_LANG_MODULE['Could not checkout repo. Somethings went wrong. Try again later'] = 'Could not checkout repo. Somethings went wrong. Try again later';
$_COS_LANG_MODULE['Could not write to file system '] = 'Could not write to file system ';
$_COS_LANG_MODULE['Could not move all HTML assets'] = 'Could not move all HTML assets';
$_COS_LANG_MODULE['You have a file in your css path which is not allowed. Found file: '] = 'You have a file in your css path which is not allowed. Found file: ';
$_COS_LANG_MODULE['Remove it from meta.yaml'] = 'Remove it from meta.yaml';
$_COS_LANG_MODULE['Epub fails! Mobi has no cover image. Specify this in a meta.yaml file'] = 'Epub fails! Mobi has no cover image. Specify this in a meta.yaml file';
$_COS_LANG_MODULE['Done '] = 'Done ';
$_COS_LANG_MODULE['Add a git repo'] = 'Add a git repo';
$_COS_LANG_MODULE['Wait while generating site. This may take a minute or two'] = 'Wait while generating site. This may take a minute or two';
$_COS_LANG_MODULE['If no error were reported, you exports has been generated. '] = 'If no error were reported, you exports has been generated. ';
$_COS_LANG_MODULE['Remove it from your repo with: git rm -f '] = 'Remove it from your repo with: git rm -f ';
$_COS_LANG_MODULE["Found illigal options in 'format-arguments': "] = "Found illigal options in 'format-arguments': ";
$_COS_LANG_MODULE['in type '] = 'in type ';
$_COS_LANG_MODULE['Error. You will need to have .md files written in markdown in your repo. No such files found!'] = 'Error. You will need to have .md files written in markdown in your repo. No such files found!';
$_COS_LANG_MODULE['Failed to create export of type: '] = 'Failed to create export of type: ';
