<?php


// Translation of file /modules/gitbook/module.php

$_COS_LANG_MODULE['Written by: '] = 'Written by: ';
$_COS_LANG_MODULE['Exports: '] = 'Exports: ';
$_COS_LANG_MODULE['Delete'] = 'Delete';
$_COS_LANG_MODULE['Checkout'] = 'Checkout';
$_COS_LANG_MODULE['Repo files has been purged!'] = 'Repo files has been purged!';
$_COS_LANG_MODULE['Repo files has been purged. Database entry has been removed!'] = 'Repo files has been purged. Database entry has been removed!';
$_COS_LANG_MODULE['Remove git repo and exported files - but leave repo in database'] = 'Remove git repo and exported files - but leave repo in database';
$_COS_LANG_MODULE['Remove everything. Be carefull as any links to this repo no longer will be found!'] = 'Remove everything. Be carefull as any links to this repo no longer will be found!';
$_COS_LANG_MODULE['Enter repo URL (http|https)'] = 'Enter repo URL (http|https)';
$_COS_LANG_MODULE['Add'] = 'Add';
$_COS_LANG_MODULE['Not a correct repo URL'] = 'Not a correct repo URL';
$_COS_LANG_MODULE['Repo already exists'] = 'Repo already exists';
$_COS_LANG_MODULE['URL does not seem to be a git repo. If you know this is a git repo, please try again.'] = 'URL does not seem to be a git repo. If you know this is a git repo, please try again.';
$_COS_LANG_MODULE['Will now checkout repo'] = 'Will now checkout repo';
$_COS_LANG_MODULE['Could not move all HTML assets'] = 'Could not move all HTML assets';
$_COS_LANG_MODULE['Could not checkout repo. Somethings went wrong. Try again later'] = 'Could not checkout repo. Somethings went wrong. Try again later';
$_COS_LANG_MODULE['Updated repo '] = 'Updated repo ';
$_COS_LANG_MODULE['Could not write to file system '] = 'Could not write to file system ';
$_COS_LANG_MODULE['You have a file in your css path which is not allowed. Found file: '] = 'You have a file in your css path which is not allowed. Found file: ';
$_COS_LANG_MODULE['Found illigal options in <span class="notranslate"><b>format-arguments</b></span>: '] = 'Found illigal options in <span class="notranslate"><b>format-arguments</b></span>: ';
$_COS_LANG_MODULE['Remove it from <b>meta.yaml</b>'] = 'Remove it from <b>meta.yaml</b>';
$_COS_LANG_MODULE['You will need to have a title and a cover image when creating MOBI files from Epub files'] = 'You will need to have a title and a cover image when creating MOBI files from Epub files';
$_COS_LANG_MODULE['Done '] = 'Done ';
$_COS_LANG_MODULE['Share this using: '] = 'Share this using: ';
$_COS_LANG_MODULE['Repo URL: '] = 'Repo URL: ';
$_COS_LANG_MODULE['Edited by: '] = 'Edited by: ';
$_COS_LANG_MODULE['Add a git repo'] = 'Add a git repo';
$_COS_LANG_MODULE['Wait while generating site. This may take a minute or two'] = 'Wait while generating site. This may take a minute or two';
$_COS_LANG_MODULE['You can not perform any action on this page.'] = 'You can not perform any action on this page.';
$_COS_LANG_MODULE['No errors reported. You exports has been generated with success. '] = 'No errors reported. You exports has been generated with success. ';
$_COS_LANG_MODULE['Remove it from your repo with: git rm -f '] = 'Remove it from your repo with: git rm -f ';
$_COS_LANG_MODULE['in type '] = 'in type ';
$_COS_LANG_MODULE['Error. You will need to have .md files written in markdown in your repo. No such files found!'] = 'Error. You will need to have .md files written in markdown in your repo. No such files found!';
$_COS_LANG_MODULE['Failed to create export of type: '] = 'Failed to create export of type: ';
