<?php

$_COS_LANG_MODULE['Delete'] = 'Slett';
$_COS_LANG_MODULE['Checkout'] = 'Kassen';
$_COS_LANG_MODULE['Repo has been deleted'] = 'Repo er slettet';
$_COS_LANG_MODULE['Confirm removal of repo'] = 'Bekreft fjerning av repo';
$_COS_LANG_MODULE['Enter repo URL (http|https)'] = 'Tast repo URL (http | https)';
$_COS_LANG_MODULE['Add'] = 'Legg';
$_COS_LANG_MODULE['Not a correct repo URL'] = 'Ikke en korrekt repo URL';
$_COS_LANG_MODULE['Repo already exists'] = 'Repo allerede eksisterer';
$_COS_LANG_MODULE['URL does not seem to be a git repo. If you know this is a git repo, please try again.'] = 'URL ser ikke ut til å være en git repo. Hvis du vet at dette er en git repo, prøv igjen.';
$_COS_LANG_MODULE['Will now checkout repo'] = 'Vil nå kassa repo';
$_COS_LANG_MODULE['Exports: '] = 'Eksport:';
$_COS_LANG_MODULE['Fetching repo '] = 'Henter repo';
$_COS_LANG_MODULE['Could not checkout repo. Somethings went wrong. Try again later'] = 'Kunne ikke kassa repo. Somethings gikk galt. Prøv igjen senere';
$_COS_LANG_MODULE['Could not write to file system '] = 'Kunne ikke skrive til filsystemet';
$_COS_LANG_MODULE['Could not move all HTML assets'] = 'Kunne ikke flytte alle HTML eiendeler';
$_COS_LANG_MODULE['You have a file in your css path which is not allowed. Found file: '] = 'Du har en fil i din css sti som ikke er tillatt. Funnet fil:';
$_COS_LANG_MODULE['Epub fails! Mobi has no cover image. Specify this in a meta.yaml file'] = 'Epub mislykkes! Mobi har ingen cover bilde. Angi dette i en meta.yaml fil';
$_COS_LANG_MODULE['Done '] = 'Ferdig';
$_COS_LANG_MODULE['Add a git repo'] = 'Legg en git repo';
$_COS_LANG_MODULE['Wait while generating site. This may take a minute or two'] = 'Vent mens generere nettstedet. Dette kan ta et minutt eller to';
$_COS_LANG_MODULE['If no error were reported, you exports has been generated. '] = 'Hvis ingen feil ble rapportert, har dere eksporten blitt generert.';
$_COS_LANG_MODULE['Remove it from your repo with: git rm -f '] = 'Fjern det fra repo med: git rm -f';
$_COS_LANG_MODULE['Error. You will need to have .md files written in markdown in your repo. No such files found!'] = 'Feil. Du må ha .md filer skrevet i Markdown i din repo. Ingen slike filer funnet!';
$_COS_LANG_MODULE['Failed to create export of type: '] = 'Klarte ikke å lage eksport av typen:';
