<?php

$_COS_LANG_MODULE['Delete'] = 'Löschen';
$_COS_LANG_MODULE['Checkout'] = 'Kasse';
$_COS_LANG_MODULE['Repo has been deleted'] = 'Repo gelöscht wurde';
$_COS_LANG_MODULE['Confirm removal of repo'] = 'Entfernung von Repo Bestätigen';
$_COS_LANG_MODULE['Enter repo URL (http|https)'] = 'Geben Repo URL (http | https)';
$_COS_LANG_MODULE['Add'] = 'Hinzufügen';
$_COS_LANG_MODULE['Not a correct repo URL'] = 'Keine korrekte Repo URL';
$_COS_LANG_MODULE['Repo already exists'] = 'Repo bereits vorhanden';
$_COS_LANG_MODULE['URL does not seem to be a git repo. If you know this is a git repo, please try again.'] = 'URL scheint nicht ein git Repo sein. Wenn Sie wissen, das ist ein git Repo, versuchen Sie es erneut.';
$_COS_LANG_MODULE['Will now checkout repo'] = 'Wird nun Kasse Repo-';
$_COS_LANG_MODULE['Exports: '] = 'Exporte:';
$_COS_LANG_MODULE['Fetching repo '] = 'Holen Repo-';
$_COS_LANG_MODULE['Could not checkout repo. Somethings went wrong. Try again later'] = 'Könnte nicht Prüfung Repo. Somethings falsch gelaufen ist. Versuchen Sie es später noch einmal';
$_COS_LANG_MODULE['Could not write to file system '] = 'Konnte nicht geschrieben in das Dateisystem';
$_COS_LANG_MODULE['Could not move all HTML assets'] = 'Alle HTML Vermögenswerte konnte nicht verschoben werden';
$_COS_LANG_MODULE['You have a file in your css path which is not allowed. Found file: '] = 'Sie haben eine Datei in Ihrem css Pfad was nicht erlaubt ist. Gefunden Datei:';
$_COS_LANG_MODULE['Found illigal options in <span class="notranslate"><b>format-arguments</b></span>: '] = 'Gefunden illigal Optionen im <b><span class="notranslate">format-arguments</span></b> :';
$_COS_LANG_MODULE['Remove it from <b>meta.yaml</b>'] = 'Entfernen Sie es aus <b>meta.yaml</b>';
$_COS_LANG_MODULE['Epub fails! Mobi has no cover image. Specify this in a meta.yaml file'] = 'Epub nicht! Mobi hat keine Cover-Bild. Geben Sie diese in einer Datei meta.yaml';
$_COS_LANG_MODULE['Done '] = 'Gemacht';
$_COS_LANG_MODULE['Add a git repo'] = 'Fügen Sie eine git Repo';
$_COS_LANG_MODULE['Wait while generating site. This may take a minute or two'] = 'Warten Sie, während die Erzeugung vor Ort. Dies kann eine Minute dauern oder zwei';
$_COS_LANG_MODULE['If no error were reported, you exports has been generated. '] = 'Wenn kein Fehler gemeldet wurden, hat man die Exporte generiert.';
$_COS_LANG_MODULE['Remove it from your repo with: git rm -f '] = 'Entfernen Sie es von Ihrem Repo mit: git rm -f';
$_COS_LANG_MODULE['in type '] = 'in Typ';
$_COS_LANG_MODULE['Error. You will need to have .md files written in markdown in your repo. No such files found!'] = 'Fehler. Sie müssen .md Dateien in Markdown in Ihrem Repo geschrieben haben. Keine solche Dateien gefunden!';
$_COS_LANG_MODULE['Failed to create export of type: '] = 'Fehler beim Export von Typ zu erstellen:';
