<?php

$_COS_LANG_MODULE['Delete'] = 'Poistaa';
$_COS_LANG_MODULE['Checkout'] = 'Kassa';
$_COS_LANG_MODULE['Repo has been deleted'] = 'Repo on poistettu';
$_COS_LANG_MODULE['Confirm removal of repo'] = 'Vahvista poisto repo';
$_COS_LANG_MODULE['Enter repo URL (http|https)'] = 'Anna Repo URL (http | https)';
$_COS_LANG_MODULE['Add'] = 'Lisätä';
$_COS_LANG_MODULE['Not a correct repo URL'] = 'Ei oikein repo URL';
$_COS_LANG_MODULE['Repo already exists'] = 'Repo jo olemassa';
$_COS_LANG_MODULE['URL does not seem to be a git repo. If you know this is a git repo, please try again.'] = 'URL-osoite ei näytä olevan git repo. Jos tiedät tämä on git repo, yritä uudelleen.';
$_COS_LANG_MODULE['Will now checkout repo'] = 'Nyt kassalle repo';
$_COS_LANG_MODULE['Exports: '] = 'Vienti:';
$_COS_LANG_MODULE['Fetching repo '] = 'Haetaan repo';
$_COS_LANG_MODULE['Could not checkout repo. Somethings went wrong. Try again later'] = 'Ei voitu kassalle repo. Somethings meni pieleen. Yritä myöhemmin uudelleen';
$_COS_LANG_MODULE['Could not write to file system '] = 'Ei voitu kirjoittaa tiedostoon järjestelmä';
$_COS_LANG_MODULE['Could not move all HTML assets'] = 'Ei voitu siirtää kaikki HTML varat';
$_COS_LANG_MODULE['You have a file in your css path which is not allowed. Found file: '] = 'Sinulla on tiedosto CSS polku, joka ei ole sallittua. Löytyi tiedosto:';
$_COS_LANG_MODULE['Epub fails! Mobi has no cover image. Specify this in a meta.yaml file'] = 'Epub epäonnistuu! Mobi ei kansikuva. Määritä tämä meta.yaml tiedostoon';
$_COS_LANG_MODULE['Done '] = 'Tehty';
$_COS_LANG_MODULE['Add a git repo'] = 'Lisää git repo';
$_COS_LANG_MODULE['Wait while generating site. This may take a minute or two'] = 'Odota luo samalla sivustolla. Tämä voi kestää minuutin tai kaksi';
$_COS_LANG_MODULE['If no error were reported, you exports has been generated. '] = 'Jos virheitä on raportoitu, voit vienti on luotu.';
$_COS_LANG_MODULE['Remove it from your repo with: git rm -f '] = 'Poista se arkistoselaimesi kanssa: git rm -f';
$_COS_LANG_MODULE['Error. You will need to have .md files written in markdown in your repo. No such files found!'] = 'Virhe. Sinun täytyy olla .md tiedostoja kirjoitettu markdown teidän repo. Ei tällaisia ​​tiedostoja löytynyt!';
$_COS_LANG_MODULE['Failed to create export of type: '] = 'Luonti epäonnistui vienti tyyppi:';
