<?php

$_COS_LANG_MODULE['Delete'] = 'Radera';
$_COS_LANG_MODULE['Checkout'] = 'Kassan';
$_COS_LANG_MODULE['Repo has been deleted'] = 'Repo har tagits bort';
$_COS_LANG_MODULE['Confirm removal of repo'] = 'Bekräfta borttagning av repan';
$_COS_LANG_MODULE['Enter repo URL (http|https)'] = 'Ange repo URL (http | https)';
$_COS_LANG_MODULE['Add'] = 'Lägga till';
$_COS_LANG_MODULE['Not a correct repo URL'] = 'Inte en riktig repa webbadress';
$_COS_LANG_MODULE['Repo already exists'] = 'Repo finns redan';
$_COS_LANG_MODULE['URL does not seem to be a git repo. If you know this is a git repo, please try again.'] = 'URL verkar inte vara en git repa. Om du vet att detta är en git repa, försök igen.';
$_COS_LANG_MODULE['Will now checkout repo'] = 'Kommer nu kassan repa';
$_COS_LANG_MODULE['Exports: '] = 'Export:';
$_COS_LANG_MODULE['Fetching repo '] = 'Hämtar repo';
$_COS_LANG_MODULE['Could not checkout repo. Somethings went wrong. Try again later'] = 'Kunde inte kassan repa. Somethings gick fel. Försök igen senare';
$_COS_LANG_MODULE['Could not write to file system '] = 'Kunde inte skriva till filen systemet';
$_COS_LANG_MODULE['Could not move all HTML assets'] = 'Det gick inte att flytta alla HTML tillgångar';
$_COS_LANG_MODULE['You have a file in your css path which is not allowed. Found file: '] = 'Du har en fil i din css bana som inte är tillåtet. Hittade fil:';
$_COS_LANG_MODULE['Epub fails! Mobi has no cover image. Specify this in a meta.yaml file'] = 'Epub misslyckas! Mobi har ingen omslagsbild. Ange detta i en meta.yaml fil';
$_COS_LANG_MODULE['Done '] = 'Klar';
$_COS_LANG_MODULE['Add a git repo'] = 'Lägg till en git repo';
$_COS_LANG_MODULE['Wait while generating site. This may take a minute or two'] = 'Vänta medan generera webbplats. Detta kan ta en minut eller två';
$_COS_LANG_MODULE['If no error were reported, you exports has been generated. '] = 'Om rapporterades inget fel, har ni exporten genererats.';
$_COS_LANG_MODULE['Remove it from your repo with: git rm -f '] = 'Ta bort det från din repo med: git rm -f';
$_COS_LANG_MODULE['Error. You will need to have .md files written in markdown in your repo. No such files found!'] = 'Fel. Du måste ha .md filer som skrivits i markdown i din repo. Inga sådana filer hittas!';
$_COS_LANG_MODULE['Failed to create export of type: '] = 'Det gick inte att skapa export av typen:';
